import CoverImage from "@/components/CoverImage";
import PageBanner from "@/components/PageBanner";
import PortSection002 from "@/components/portSection002";
import PortSection003 from "@/components/portSection003";

export default function Page() {
  const description = `
  Commercial infrastructure resources are used to produce private goods. Basic manufacturing processes, such as die casting, milling, and the assembly line process, 
  are nonrival inputs into the production of a wide variety of private manufactured goods. Basic agricultural processes and food processing techniques similarly are 
  nonrival inputs into the production of a wide variety of private agricultural goods and foodstuffs. Many commercial infrastructure resources are used productively
   by suppliers purely as a delivery mechanism for manufactured goods, agricultural goods, foodstuffs, and many other commercial products. A cable television system,
    for example, acts as an input into the delivery of content purely for consumption by an end–user. Content providers use the infrastructure to provide a private 
    service to the consumer (delivery of content for consumption) under conditions that render the output rivalrous and excludable. At least in theory,
   a wide variety of content suppliers can deliver a wide variety of content under such conditions. The Internet and road systems similarly are used by a wide range of 
   suppliers to delivery private goods and services.

Infrastructure users that produce public goods and non–market goods suffer valuation problems because they generally do not fully measure or appropriate the (potential)
 benefits of the outputs they produce and consequently do not accurately represent actual social demand for the infrastructure resource. Instead, for public and social 
 infrastructure, demand generated by competitive output markets will tend to reflect the individual benefits realized by a particular user and not take into account positive
  externalities. To the extent that individuals’ willingness to pay for access to infrastructure reflects only the value that they will realize from an output, the market mechanism
   will not fully take into account (or provide the services for) the broader set of social benefits attributable to the public goods or non–market goods. Infrastructure consumers will
    pay for access to infrastructure only to the extent that they benefit (rather than to the extent that society benefits) from the outputs produced. Difficulties in measuring and appropriating 
    value generated in output markets translate into a valuation/measurement problem for infrastructure suppliers. Competitive output markets may fail to accurately manifest demand for public and 
    social infrastructure because of the presence of demand–side externalities.


Public and social infrastructure resources are used to produce public goods and non-market goods, respectively. For both public and social infrastructure, the ability of competitive
 output markets to effectively generate and process information regarding demand for the required input is less clear than in the case of commercial infrastructure.


 Infrastructure users that produce public goods and non–market goods suffer valuation problems because they generally do not fully measure or appropriate the (potential) benefits of 
 the outputs they produce and consequently do not accurately represent actual social demand for the infrastructure resource. Instead, for public and social infrastructure, demand generated
  by competitive output markets will tend to reflect the individual benefits realized by a particular user and not take into account positive externalities. To the extent that individuals’
  willingness to pay for access to infrastructure reflects only the value that they will realize from an output, the market mechanism will not fully take into account (or provide the services
   for) the broader set of social benefits attributable to the public goods or non–market goods. Infrastructure consumers will pay for access to infrastructure only to the extent that they benefit 
   (rather than to the extent that society benefits) from the outputs produced. Difficulties in measuring and appropriating value generated in output markets translate into a valuation/measurement 
   problem for infrastructure suppliers. Competitive output markets may fail to accurately manifest demand for public and social infrastructure because of the presence of demand–side externalities.
`;
  return (
    <div>
            {/* Background Section */}
            <PageBanner title="Commercial Infrastructure"/>

            {/* Main Content */}
            <div className="max-w-7xl mx-auto px-6 py-10">
            <div>
                <CoverImage
                  imageSrc="/images/portfolio-Commercial.jpg" // Replace with the image path
                  altText="Industrial Warehouse"
                />
              </div>
              {/* Port Section 001 */}
              <div className="bg-white rounded-lg  overflow-hidden mb-12">
                <PortSection003
                 // imageSrc="/images/portfolio-Commercial.jpg"
                  category="Business Planning"
                  title="What Does Commercial-Infrastructure Mean?"
                  description={description}
                />
              </div>
            </div>


            {/* Divider */}
            <hr className="border-t border-gray-300 mb-12" />

            {/* Related Portfolio */}
            <div className="bg-white rounded-lg p-6">
            {/* <h2 className="text-2xl font-bold text-gray-800 mb-6">Related Portfolio</h2> */}
            <PortSection002 />
            </div>
      </div>
  );
}

